trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
  - group: 'Prod Management Resources'
  - name: buildConfiguration
    value: 'release'
  - group: "BUILD Management Resources"

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.63
    endpoint: SkillsFundingAgency

jobs:
- job: 'CodeBuild'
  pool:
    name: DAS - Continuous Integration Agents
    demands: LATEST_DOTNET_VERSION -equals 3.1
  workspace:
    clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloud: true
      SonarCloudProjectKey: SkillsFundingAgency_das-coursedelivery-api

  - task: DotNetCoreCLI@2
    displayName: 'Publish Website'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.CourseDelivery.Api/SFA.DAS.CourseDelivery.Api.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'

- job: 'DACPACBuild'
  pool:
    name: 'DAS - Continuous Integration'
    demands: Agent.OS -equals Windows_NT
  workspace:
    clean: all
  steps:
  - task: VSBuild@1
    displayName: 'Build DACPAC'
    inputs:
      solution: 'src/SFA.DAS.CourseDelivery.Database/SFA.DAS.CourseDelivery.Database.sqlproj'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: '/p:PackageLocation="$(build.artifactstagingdirectory)/publish"'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      contents: |
        src/**/*.dacpac
      targetFolder: '$(build.artifactstagingdirectory)/publish'
  - task: PublishBuildArtifacts@1